### ISSUE TITLE
what's the point of the output results file?

### ISSUE THREAD

**Issue by FarisHijazi** [jankrepl/mltype#108]
I was hoping that the `mlt file --output-file results.txt` option was to save the statistics (WPM and accuracy)
because I run this as a script and I then plot the accuracy over a few days.

however when I open the results.txt it's all garbage:

```
�^D��^D^@^@^@^@^@^@(�^W#force_color_prompt=yes�]�(]��^Kmltype.base��^FAction���)��}�(�^Kpressed_key��^A#��^Fstatus�K^B�^Bts��^Hdatetime��^Hdatetime���C
^G�^H^D^R^G(^B�ʔ��R�uba]�h^E)��}�(h^H�^Af�h
K^Bh^Kh^NC
^G�^H^D^R^G(^F�t���R�uba]�h^E)��}�(h^H�^Ao�h
K^Bh^Kh^NC
^G�^H^D^R^G(^H�j���R�uba]�h^E)��}�(h^H�^Ar�h
K^Bh^Kh^NC
^G�^H^D^R^G(    �(���R�uba]�h^E)��}�(h^H�^Ac�h
K^Bh^Kh^NC
^G�^H^D^R^G(^L:����R�uba]�h^E)��}�(h^H�^Ae�h
K^Bh^Kh^NC
^G�^H^D^R^G(^N� R�uba]�h^E)��}�(h^H�^A_�h
K^Bh^Kh^NC
^G�^H^D^R^G)^B�ꔅ�R�uba]�h^E)��}�(h^Hh*h
K^Bh^Kh^NC
^G�^H^D^R^G)^E"˔��R�uba]�h^E)��}�(h^Hh^\h
K^Bh^Kh^NC
^G�^H^D^R^G)^F�L���R�uba]�h^E)��}�(h^H�^Al�h
K^Bh^Kh^NC
^G�^H^D^R^G)^Hݸ���R�uba]�h^E)��}�(h^Hh^\h
K^Bh^Kh^NC
^G�^H^D^R^G)^K9F���R�uba]�h^E)��}�(h^Hh#h
K^Bh^Kh^NC
^G�^H^D^R^G)^L�h���R�uba]�(h^E)��}�(h^H�^A=�h
K^Ch^Kh^NC
^G�^H^D^R^G*^@�ǔ��R�ubh^E)��}�(h^Hh8h
K^Bh^Kh^NC
^G�^H^D^R^G*
U^M���R�ube]�(h^E)��}�(h^HNh
K^Ah^Kh^NC
^G�^H^D^R^G*^G(^S���R�ubh^E)��}�(h^H�^Ap�h
K^Bh^Kh^NC
^G�^H^D^R^G*^N{����R�ube]�h^E)��}�(h^Hh#h
```

**Comment by jankrepl** [comment]
@FarisHijazi Great question. It is actually a pickle file that is not supposed to be directly "readable".

To load it use the `TypedText.load` `classmethod` - see more info below. The class `TypedText` has a lot of methods that correspond to various statistics you might be interested in.

https://github.com/jankrepl/mltype/blob/master/mltype/base.py#L51-L105

And to answer your question "What is the point of this file"?
In `mltype` you can actually "compete" against your past attempts and this file holds all the information necessary about that "attempt".
* Start timestamp
* End timestamp
* The target text you were typing
* Actions - a list of Actions (https://github.com/jankrepl/mltype/blob/master/mltype/base.py#L12-L30) which are nothing else then a collection of timestamp + key you pressed

Note that with the knowledge of the above you can actually implement even custom metrics (not just speed + accuracy) or create fancy plots.

**Comment by FarisHijazi** [comment]
Ok sounds good, I would maybe write the word pickle in the --help to make it more clear

**Comment by jankrepl** [comment]
That is a legit point. At least now it is documented in this issue. If more people find it confusing I can definitely adjust the`--help` and the docs. Or of course feel free to create a PR.

Anyway, I am going to close this issue (however, we can reopen it if need be).
