### ISSUE TITLE
Error when Installing on Windows

### ISSUE THREAD

**Issue by AbhayAysola** [jankrepl/mltype#81]
`    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-30ah4gz4\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-30ah4gz4\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-h4a25iwr'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-30ah4gz4\torch\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-30ah4gz4\torch\setup.py", line 147, in <module>
        import numpy as np
      File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\numpy\__init__.py", line 138, in <module>
        from . import _distributor_init
      File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\numpy\_distributor_init.py", line 26, in <module>
        WinDLL(os.path.abspath(filename))
      File "c:\python38\lib\ctypes\__init__.py", line 373, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 is not a valid Win32 application
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I've gotten this error when trying to install using `pip` on a windows machine. I've also tried installing using `pipenv`. Same error when installing from github directly by cloning and running `pip install -e .` as shown in the docs.

**Comment by AbhayAysola** [comment]
Update: I've searched around a little, and the problem seems to arise from a dependency problem or architecture mismatch. I will do a little more research and get back to you. AFAIK this error is not a problem woth your code.

**Comment by AbhayAysola** [comment]
Al right, so turns out my Python installation was acting up because of polluted environment issues so I did a clean install. I also installed PyTorch from the website instead of the `pip install torch` and it works now.

**Comment by AbhayAysola** [comment]
Welp I spoke too soon. The package is installed but when I try to use any command I get `ModuleNotFoundError: No module named '_curses'`
I did `mlt raw <random text here>`

**Comment by AbhayAysola** [comment]
Turns out curses has a problem on windows systems, so I used `pip install windows-curses` and it finally works.

**Comment by jankrepl** [comment]
Hey there, sorry if you had to struggle too much! Hopefully everything is working now!
I opened a ticket motivated by your issue  - #83

**Comment by AbhayAysola** [comment]
It works perfectly now, I'll be starting to look into it soon. I've got into touch typing very recently via a website called [keybr.com ](keybr.com). I now have improved my typing speed but unfortunately keybr.com didn't have support for custom training data which is very helpful. Thanks for making this tool :)

**Comment by jankrepl** [comment]
I am happy you like it:)
