### ISSUE TITLE
New Model Request

### ISSUE THREAD

**Issue by amacgregor** [jankrepl/mltype#92]
Great project! Can you please train a model for Elixir ?

**Comment by jankrepl** [comment]
Sure! Can you suggest a good github repo? Or shall I just pick a repo with a lot of stars?:)

**Comment by amacgregor** [comment]
https://github.com/phoenixframework/phoenix (https://link.getmailspring.com/link/F17B81DF-BED5-4282-A111-947EDAC0E737@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fphoenixframework%2Fphoenix&recipient=cmVwbHkrQUFCVFpTTVRVUllOVlYzTTZRUjVBRVY1V1A1R1pFVkJOSEhDWUJFUldJQHJlcGx5LmdpdGh1Yi5jb20%3D) is probably a great choice for this!

Allan MacGregor
Senior Software Engineer

P: +1 (647) 916-3590 (tel:+1%20(647)%20916-3590)
W: http://allanmacgregor.com (https://link.getmailspring.com/link/F17B81DF-BED5-4282-A111-947EDAC0E737@getmailspring.com/1?redirect=http%3A%2F%2Fallanmacgregor.com&recipient=cmVwbHkrQUFCVFpTTVRVUllOVlYzTTZRUjVBRVY1V1A1R1pFVkJOSEhDWUJFUldJQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by jankrepl** [comment]
Should I include both the `.ex` and `.exs` extensions? Or just one of them?

**Comment by amacgregor** [comment]
Both of them, please.

Allan MacGregor
Senior Software Engineer

P: +1 (647) 916-3590 (tel:+1%20(647)%20916-3590)
W: http://allanmacgregor.com (https://link.getmailspring.com/link/B4DEC03D-A667-4481-AE37-DEBA6333BCA4@getmailspring.com/0?redirect=http%3A%2F%2Fallanmacgregor.com&recipient=cmVwbHkrQUFCVFpTTkhVWEwyNERPVDZXVFU2QUY1V1A2M1JFVkJOSEhDWUJFUldJQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by jankrepl** [comment]
Added to master, hopefully it is good enough:

```
mlt sample -n 1000 -r 10 elixir
```

```
ing halted s, not is_nil(assigns) = System.monotonic_time() end # Aliases are shown a: ?transport @endpoint Endpoint :ok end end # Resuurc url with raises unalload to binary/, fn -> Gen.Html.run(~w(Blog Postext prive     = Mix.
Phoenix.action_fallback(Plug.Conn.t, [String.t) :: String.t ) @compile_config :browser || ?] end # No option in some in: mix.ex(:format_encoders, client_refute_push("/", template_engines: [], [\", \":\"e\nAssword])" end assert_
file "lib/phoenix_web/live/blog/post_live/index.ex", fn file -> assert file =~ "database: "pong subscribe" |> assign(:page_title, "Test") ] = push(socket, "event3", payload: "kee"), payload: {:binary, data}} = state) do {:reply
, {String.t, _)} end end defmodule Endpoint do use Phoenix.Template, root: Path.join(socket_munfunker_sult() Keep socket_ref = conn[) |> with_session |> render(:f, -5) |> put_resp_header("ocket", "foo") |> render(200, connect_i
nfo, ref) {_, ref :: buile_connect(ref) end end def call(conn, endpoint, handler, opts) do P  
```

**Comment by amacgregor** [comment]
Downloading and trying it out!

Allan MacGregor
Senior Software Engineer

P: +1 (647) 916-3590 (tel:+1%20(647)%20916-3590)
W: http://allanmacgregor.com (https://link.getmailspring.com/link/B7AC30DE-A821-42CA-8F14-F812EB5F3E75@getmailspring.com/0?redirect=http%3A%2F%2Fallanmacgregor.com&recipient=cmVwbHkrQUFCVFpTT1RLQk9PV0VKRzVPM1JOR041V1FXU0xFVkJOSEhDWUJFUldJQHJlcGx5LmdpdGh1Yi5jb20%3D)
