### ISSUE TITLE
Would it bother you to provide alternative download links for the models?

### ISSUE THREAD

**Issue by septsea** [jankrepl/mltype#97]
I am a Chinese student not good at typing. I am very happy to discover the project! At least I can practice typing much more easily. However, I cannot access certain foreign services like Google without a VPN. I cannot afford a stable VPN, so I cannot download the models listed on `README.md`.

Would it bother you to provide alternative download links for the models?

Thanks.

**Comment by jankrepl** [comment]
Thank you for your interest!

Sure, no problem. Could you please suggest a hosting server that would be ok for you?

**Comment by septsea** [comment]
It's so nice of you! What about distributing them as Github releases? This works (almost) everywhere. In this way, you do not have to create extra accounts.

**Comment by jankrepl** [comment]
Interesting idea:) AFAIK releases are always linked to a specific tag of the source code whereas the models should be useable inside of all versions. However, I have to admit that it looks really convenient. I will look into it a little bit more and unless I find some problems I will create a release and put all the model binaries inside:)

**Comment by septsea** [comment]
Creating a new repository for storing models might works.

**Comment by jankrepl** [comment]
I gave it a thought and I would prefer to do it outside of GitHub. Can you point me to a hosting service that is available in China and where I could upload all the models (~500MB)?

**Comment by septsea** [comment]
Well, I don't really know what real hosting services are available worldwide. In China, the hosting service used most is probably https://yun.baidu.com/, but this is slow without a premium account. A better but less well-known service is https://www.lanzou.com/, but each file must not exceed 100 MB.

You could list what hosting services are available in your country, too.

In my opinion, GitHub is not a bad choice, but if you prefer to do it outside of GitHub, that's OK. I believe that we will find a service available worldwide.

**Comment by jankrepl** [comment]
I am struggling to register on those sites (since I do not have a Chinese phone number). Feel free to shoot me an email `kjan.official@gmail.com` and we can figure something out.
