### ISSUE TITLE
SQL Training

### ISSUE THREAD

**Issue by mikhael28** [jankrepl/mltype#98]
I would love a trained set on SQL. I'm using this application as a piece of 'homework' for teaching my friend SQL, love it!

**Comment by jankrepl** [comment]
Hey there:)

I can definitely train a model for you, however, do you know about any dataset/repo that contains a lot of SQL code/queries?

**Comment by mikhael28** [comment]
Hey there! Sorry for the delay here. I actually went ahead and built my own quick touch typing editor with React, going to be using it to create a product for myself, a friend and to train on SQL/JS algorithms. The CLI installation process, especially with Docker + random dependency installs, was too much for a non-technical person. Plus, me running on an M1, I think the compatibility may not have been tested. Probably my fault, not yours - could have tried installing with Rosetta.

Regarding SQL, I can't think of a repository off the top of my head with a lot of SQL queries.
